name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - main-preview

jobs:
  build-and-deploy-main:
    name: Build and Deploy Main Site
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build

      - uses: actions/upload-pages-artifact@v4
        with:
          path: build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  build-and-deploy-preview:
    name: Build and Deploy Preview Site
    if: github.ref == 'refs/heads/main-preview'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci
      
      - name: Build website for preview
        run: npm run build
        env:
          DOCUSAURUS_BASE_URL: /shop-document/preview/
        
      - name: Deploy to gh-pages (preview subdirectory)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: preview
          keep_files: true
